### PR TITLE
Add updater script (for users)

### PR DESCRIPTION
**Pull request by DerGoogler**
Also added install instructions to the readme file

### CODE REVIEW

**Comment by schmaldeo** [comment]
I really appreciate the effort, however, could you provide a real-life use case for this? I feel like it's just overcomplicating something that can be done by opening the releases page and searching for the desired version (should always have the latest one anyway).

**Comment by DerGoogler** [comment]
@schmaldeo thanks. It downloads the selected releases into C:\Program Files\DS4Windows without having to open chrome, unpack etc

**Comment by schmaldeo** [comment]
I'd say if you add an option to choose between hand-picked version and latest (with an emphasis on latest too) I can merge.

**Comment by DerGoogler** [comment]
I have updated the script:

- Users can now select if they wanna install the latest version or enter specific version to download
- Also removed the admin requirement
- DS4Windows is now placed in `C:\Users\<USER>\AppData\Local\DS4Windows`

**Comment by schmaldeo** [comment]
Thank you for the contribution :)

**Comment by DerGoogler** [comment]
@schmaldeo I'm think I'm gonna fork the DS4Updater instead. I've seem that you also update the `newest.txt` file and I wanna try something new ;)

**Comment by schmaldeo** [comment]
It's a legacy option now, due to https://github.com/schmaldeo/DS4Windows/pull/16/commits/4c7e439aa2a34efdb889acca3d0ed4ca361d22f0.

newest.txt update for v3.7.3 was the last one required, as from now on the latest version number is not checked against that file, but rather against GitHub API.

The updater could maybe do with a bit of a refresh (the only work I've done on it was change the links to point to my repos rather than Ryochan's), but I've seen that @major-sanyi also forked it.

**Comment by DerGoogler** [comment]
I've already done a bit

image

GitHub API may be a lot of requests and ending in a rate limit

**Comment by DerGoogler** [comment]
@schmaldeo I'm using `https://raw.githubusercontent.com/schmaldeo/DS4Windows/d1322d9114cf7058e383675d338df8f7d26c1790/DS4Windows/DS4WinWPF.csproj` to greo the latest release from `<Version>`, so `newest.txt` it not really a need

**Comment by major-sanyi** [comment]
> I've already done a bit
> 
> image
> 
> GitHub API may be a lot of requests and ending in a rate limit

The rate limit for unathenticated requests are 60 per hour per IP. Unless someone spams the check update, I don't think the rate limit is reached realistically. 
And it's possible to get all of  the releases in 1 go if you want to experiment with Different versions.

https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

https://api.github.com/repos/schmaldeo/DS4Windows/releases

**Pull request merged**
